/**
 * 
 * @author Daniel Espling (<a href="mailto:espling@cs.umu.se">espling@cs.umu.se</a>)
 * Copyright (C) 2011 Umea University
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package eu.optimis_project.monitoring;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class Measurement {
    private String data;
    private String name;
    private String serviceID;
    private long timestamp;
    private String instanceID;

    public Measurement() {
    }

    public Measurement(String serviceID, String instanceID, String name, String data, long timestamp) {
        this.serviceID = serviceID;
        this.instanceID = instanceID;
        this.name = name;
        this.data = data;
        this.timestamp = timestamp;
    }

    public void setData(String data) {
        this.data = data;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setServiceID(String serviceID) {
        this.serviceID = serviceID;
    }
    
    public void setInstanceID(String instanceID) {
        this.instanceID = instanceID;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

	public String getServiceID() {
		return serviceID;
	}
	
	public String getInstanceID() {
        return instanceID;
    }

	public String getData() {
		return data;
	}

	public long getTimestamp() {
		return timestamp;
	}

	public String getName() {
		return name;
	}
	

	/* Below methods are generated by Eclipse */

	@Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((data == null) ? 0 : data.hashCode());
        result = prime * result + ((instanceID == null) ? 0 : instanceID.hashCode());
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        result = prime * result + ((serviceID == null) ? 0 : serviceID.hashCode());
        result = prime * result + (int) (timestamp ^ (timestamp >>> 32));
        return result;
    }

	@Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Measurement other = (Measurement) obj;
        if (data == null) {
            if (other.data != null)
                return false;
        } else if (!data.equals(other.data))
            return false;
        if (instanceID == null) {
            if (other.instanceID != null)
                return false;
        } else if (!instanceID.equals(other.instanceID))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        } else if (!name.equals(other.name))
            return false;
        if (serviceID == null) {
            if (other.serviceID != null)
                return false;
        } else if (!serviceID.equals(other.serviceID))
            return false;
        if (timestamp != other.timestamp)
            return false;
        return true;
    }

	@Override
    public String toString() {
        return "Measurement [data=" + data + ", name=" + name + ", serviceID=" + serviceID + ", timestamp="
                + timestamp + ", instanceID=" + instanceID + "]";
    }

    public boolean validate() {
        return (data != null && name != null && serviceID != null && instanceID != null);
        // XXX Expand validation
    }
	
	
}
