#!/bin/bash
#
# Copyright (c) 2012 OPTIMIS - National Technical University of Athens
#
# chkconfig: 2345 90 60
# description: Optimis datamanager mount shared storage
#
### BEGIN INIT INFO
# Provides:          optimis-datamanager
# Required-Start:    $network
# Required-Stop:
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: optimis-datamanager mounts shared storage
# Description:       
#  Optimis datamanager mounts a shared storage in optimis distributed
#  file system.
### END INIT INFO

# Check for missing binaries
OPTIMIS_MOUNT_BIN=/usr/bin/optimis-mount
test -x $OPTIMIS__MOUNT_BIN || { echo "$OPTIMIS_MOUNT_BIN not installed";
if [ "$1" = "stop" ]; then exit 0;
else exit 5; fi; }

OPTIMIS_UMOUNT_BIN=/usr/bin/optimis-umount
test -x $OPTIMIS_UMOUNT_BIN || { echo "$OPTIMIS_UMOUNT_BIN not installed";
if [ "$1" = "stop" ]; then exit 0;
else exit 5; fi; }

OPTIMIS_CONF=/etc/datamanager.conf
test -r $OPTIMIS_CONF || { echo "$OPTIMIS_CONF not installed";
if [ "$1" = "stop" ]; then exit 0;
else exit 5; fi; }

case "$1" in
  start)
    echo "Starting Optimis Datamanager Mounting Operation "
    /usr/bin/optimis-mount
    ;;
  stop)
    echo "Stopping Optimis Datamanager Umounting Operation"
    /usr/bin/optimis-umount     
    ;;
  *)
    echo "Usage: /etc/init.d/optimis-datamanager {start|stop}"
    exit 1
    ;;
esac

exit 0

