/*
 * This file is part of the Venus-C project, released under GNU LGPL v3
 * (see LICENSE.txt file).
 *
 * Copyright Engineering Ingegneria Informatica S.p.a. 2011
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.10 at 04:50:45 PM CEST 
//


package org.opennebula.xmlschema.vnet_1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opennebula.vnet_1_new package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VNET_QNAME = new QName("http://opennebula.org/XMLSchema", "VNET");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opennebula.vnet_1_new
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TemplateTypeNetwork }
     * 
     */
    public TemplateTypeNetwork createTemplateTypeNetwork() {
        return new TemplateTypeNetwork();
    }

    /**
     * Create an instance of {@link LEASE }
     * 
     */
    public LEASE createLEASE() {
        return new LEASE();
    }

    /**
     * Create an instance of {@link VNET }
     * 
     */
    public VNET createVNET() {
        return new VNET();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VNET }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://opennebula.org/XMLSchema", name = "VNET")
    public JAXBElement<VNET> createVNET(VNET value) {
        return new JAXBElement<VNET>(_VNET_QNAME, VNET.class, null, value);
    }

}
