/*
 * This file is part of the Venus-C project, released under GNU LGPL v3
 * (see LICENSE.txt file).
 *
 * Copyright Engineering Ingegneria Informatica S.p.a. 2011
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.10 at 04:50:45 PM CEST 
//


package org.opennebula.xmlschema.vnet_1;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TemplateTypeNetwork complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TemplateTypeNetwork">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CONTEXT" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="BRIDGE" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NETWORK_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NETWORK_SIZE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TemplateTypeNetwork", propOrder = {
    "context",
    "bridge",
    "name",
    "networkaddress",
    "networksize",
    "type"
})
public class TemplateTypeNetwork {

    @XmlElement(name = "CONTEXT", namespace = "http://opennebula.org/XMLSchema", required = true)
    protected Object context;
    @XmlElement(name = "BRIDGE", namespace = "http://opennebula.org/XMLSchema")
    protected BigInteger bridge;
    @XmlElement(name = "NAME", namespace = "http://opennebula.org/XMLSchema")
    protected String name;
    @XmlElement(name = "NETWORK_ADDRESS", namespace = "http://opennebula.org/XMLSchema")
    protected String networkaddress;
    @XmlElement(name = "NETWORK_SIZE", namespace = "http://opennebula.org/XMLSchema")
    protected String networksize;
    @XmlElement(name = "TYPE", namespace = "http://opennebula.org/XMLSchema")
    protected BigInteger type;

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCONTEXT() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCONTEXT(Object value) {
        this.context = value;
    }

    /**
     * Gets the value of the bridge property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBRIDGE() {
        return bridge;
    }

    /**
     * Sets the value of the bridge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBRIDGE(BigInteger value) {
        this.bridge = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the networkaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNETWORKADDRESS() {
        return networkaddress;
    }

    /**
     * Sets the value of the networkaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNETWORKADDRESS(String value) {
        this.networkaddress = value;
    }

    /**
     * Gets the value of the networksize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNETWORKSIZE() {
        return networksize;
    }

    /**
     * Sets the value of the networksize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNETWORKSIZE(String value) {
        this.networksize = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTYPE(BigInteger value) {
        this.type = value;
    }

}
