/*
 * This file is part of the Venus-C project, released under GNU LGPL v3
 * (see LICENSE.txt file).
 *
 * Copyright Engineering Ingegneria Informatica S.p.a. 2011
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.10 at 04:50:45 PM CEST 
//


package org.opennebula.xmlschema.vnet_1;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VNET complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VNET">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="BRIDGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PUBLIC" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="TEMPLATE" type="{http://opennebula.org/XMLSchema}TemplateTypeNetwork"/>
 *         &lt;element name="LEASES" type="{http://opennebula.org/XMLSchema}LEASE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VNET", propOrder = {
    "id",
    "uid",
    "name",
    "type",
    "bridge",
    "_public",
    "template",
    "leases"
})
public class VNET {

    @XmlElement(name = "ID", namespace = "http://opennebula.org/XMLSchema", required = true)
    protected BigInteger id;
    @XmlElement(name = "UID", namespace = "http://opennebula.org/XMLSchema", required = true)
    protected BigInteger uid;
    @XmlElement(name = "NAME", namespace = "http://opennebula.org/XMLSchema", required = true)
    protected String name;
    @XmlElement(name = "TYPE", namespace = "http://opennebula.org/XMLSchema", required = true)
    protected BigInteger type;
    @XmlElement(name = "BRIDGE", namespace = "http://opennebula.org/XMLSchema", required = true)
    protected String bridge;
    @XmlElement(name = "PUBLIC", namespace = "http://opennebula.org/XMLSchema", required = true)
    protected BigInteger _public;
    @XmlElement(name = "TEMPLATE", namespace = "http://opennebula.org/XMLSchema", required = true)
    protected TemplateTypeNetwork template;
    @XmlElement(name = "LEASES", namespace = "http://opennebula.org/XMLSchema", required = true)
    protected LEASE leases;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUID() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUID(BigInteger value) {
        this.uid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTYPE(BigInteger value) {
        this.type = value;
    }

    /**
     * Gets the value of the bridge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBRIDGE() {
        return bridge;
    }

    /**
     * Sets the value of the bridge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBRIDGE(String value) {
        this.bridge = value;
    }

    /**
     * Gets the value of the public property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPUBLIC() {
        return _public;
    }

    /**
     * Sets the value of the public property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPUBLIC(BigInteger value) {
        this._public = value;
    }

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateTypeNetwork }
     *     
     */
    public TemplateTypeNetwork getTEMPLATE() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateTypeNetwork }
     *     
     */
    public void setTEMPLATE(TemplateTypeNetwork value) {
        this.template = value;
    }

    /**
     * Gets the value of the leases property.
     * 
     * @return
     *     possible object is
     *     {@link LEASE }
     *     
     */
    public LEASE getLEASES() {
        return leases;
    }

    /**
     * Sets the value of the leases property.
     * 
     * @param value
     *     allowed object is
     *     {@link LEASE }
     *     
     */
    public void setLEASES(LEASE value) {
        this.leases = value;
    }

}
