
package es.arsys;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "serviceManagerSoap", targetNamespace = "http://arsys.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceManagerSoap {


    /**
     * 
     * @param imageFilename
     * @param arch
     * @param serviceId
     * @param mem
     * @param cpu
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://arsys.es/createVM")
    @WebResult(name = "createVMResult", targetNamespace = "http://arsys.es/")
    @RequestWrapper(localName = "createVM", targetNamespace = "http://arsys.es/", className = "es.arsys.CreateVM")
    @ResponseWrapper(localName = "createVMResponse", targetNamespace = "http://arsys.es/", className = "es.arsys.CreateVMResponse")
    public String createVM(
        @WebParam(name = "service_id", targetNamespace = "http://arsys.es/")
        String serviceId,
        @WebParam(name = "image_filename", targetNamespace = "http://arsys.es/")
        String imageFilename,
        @WebParam(name = "cpu", targetNamespace = "http://arsys.es/")
        String cpu,
        @WebParam(name = "mem", targetNamespace = "http://arsys.es/")
        String mem,
        @WebParam(name = "arch", targetNamespace = "http://arsys.es/")
        String arch);

    /**
     * 
     * @param serviceId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://arsys.es/getServiceData")
    @WebResult(name = "getServiceDataResult", targetNamespace = "http://arsys.es/")
    @RequestWrapper(localName = "getServiceData", targetNamespace = "http://arsys.es/", className = "es.arsys.GetServiceData")
    @ResponseWrapper(localName = "getServiceDataResponse", targetNamespace = "http://arsys.es/", className = "es.arsys.GetServiceDataResponse")
    public String getServiceData(
        @WebParam(name = "service_id", targetNamespace = "http://arsys.es/")
        String serviceId);

    /**
     * 
     * @param serviceId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://arsys.es/terminateService")
    @WebResult(name = "terminateServiceResult", targetNamespace = "http://arsys.es/")
    @RequestWrapper(localName = "terminateService", targetNamespace = "http://arsys.es/", className = "es.arsys.TerminateService")
    @ResponseWrapper(localName = "terminateServiceResponse", targetNamespace = "http://arsys.es/", className = "es.arsys.TerminateServiceResponse")
    public String terminateService(
        @WebParam(name = "service_id", targetNamespace = "http://arsys.es/")
        String serviceId);

}
