#!/usr/bin/env python
# OPTIMIS DATAMANAGER MOUNTING SCRIPT

import os
import base64
import json
import socket

DMconfFileName = "DM.key"

def isAlive(addr, port):
	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(5)
	try:
		s.connect((addr, port))
		s.close()
		return True
	except socket.error, msg:
		s.close()
		return False


def checkIP(internal, external):
	if isAlive(internal, 22):
		return internal
	else:
		if isAlive(external, 22):
			return external
		else:
			print "Error: connection cannot be established!"
			quit()	
	
if not os.path.exists(DMconfFileName):
	print "Error: Cannot find DM.key in ", DMconfFileName
	quit()

DMconf = open(DMconfFileName, 'r').read()
DMconf = base64.b64decode(DMconf)
settings = json.loads(DMconf)

provider     = settings['provider']
intIPaddress = settings['ipaddress']
extIPaddress = settings['ipaddressPub']
key          = settings['key']
path         = settings['path']
cmd          = settings['cmd']

datamanager = checkIP(intIPaddress, extIPaddress)

print datamanager

sshkey = open('/etc/DMkey.ssh', 'w')
sshkey.write(base64.b64decode(key))
sshkey.close()
os.system("chmod go-rwx /etc/DMkey.ssh")

#os.system("fuser -m -k /storage/*   > /dev/null 2>&1")
os.system("fusermount -u /storage  > /dev/null 2>&1")                                        
os.system("umount -l /storage  > /dev/null 2>&1")                                            
os.system("rmdir /storage > /dev/null 2>&1") 
os.system("mkdir /storage")


cmd = cmd % datamanager
os.system(cmd)


