#!/bin/bash

###
#
# Author: Pierre Gilet
# Version: 1.0
# Date: 2011-02-20
#
# Description:
# Check the mcelog file for hardware errors.
#
###

# For FLEXIANT ENHANCED
# HARDWAREERROROUT=/var/cache/nagios3/check_optimis_hardware_error.out
# For other infrastructure providers
HARDWAREERROROUT=/usr/local/nagios/var/check_optimis_hardware_error.out

NEWERRORCOUNT=$(grep -ic "hardware error" /var/log/mcelog)

# Check existence of file.
if [ -e $HARDWAREERROROUT ]
then
   OLDERRORCOUNT=$(grep "Hardware error count" $HARDWAREERROROUT | cut -d "=" -f 2 | sed "s/ *//")
   # Check if it is a number.
   if [ $( echo $OLDERRORCOUNT | sed "s/^[-+0-9][0-9]*//" | wc -c ) -ne 1 ]
   then
       OLDERRORCOUNT=0
   fi
else
   OLDERRORCOUNT=0
fi

echo "File automatically generated by the script $0"  > $HARDWAREERROROUT
echo "Hardware error count=$NEWERRORCOUNT"           >> $HARDWAREERROROUT

# Check if error count has increased since the since check.
if [ $NEWERRORCOUNT -gt $OLDERRORCOUNT ]
then
   echo "Hardware error"
else
   echo "N/A"
fi

